version: "3"
services:
  nacos:
    image: nacos/nacos-server:2.0.0
    container_name: nacos-standalone-mysql
    env_file:
      - ./env/nacos-mysql.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./config/nacos-custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: always
  mysql:
    container_name: mysql
    image: nacos/nacos-mysql:8.0.16
    env_file:
      - ./env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3366:3306"