# Default values for demo.
# This is a YAML-formatted file.

secretName: ingress-secret-default
host: service.zhangyongqiao.com

project:
  host: service.zhangyongqiao.com
  image: ccr.ccs.tencentyun.com/windwithlife/project
  app_name: project
  service:
    port: 80
  ingress:
    path: /project
    
account:
  image: ccr.ccs.tencentyun.com/windwithlife/accountcenter
  app_name: account
  service:
    port: 80
  ingress:
    path: /simple-account  

connection:
  image: ccr.ccs.tencentyun.com/windwithlife/connection-service
  app_name: connection
  service:
    port: 80
  ingress:
    path: /connection-service

common:
  image: ccr.ccs.tencentyun.com/windwithlife/common-service
  app_name: common-server
  service:
    port: 80
  ingress:
    path: /common-service
   