apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  SPRING_PROFILES_ACTIVE: prod
  SERVER_PORT: "80"

  DOMAIN_NAME: bihuioo.com
  SENTRY_DSN: "https://80aaf4ae889b414f9fe72e3904cd5246@sentry.io/1380198"
  SOA_GATEWAY: api.bihuioo.com

  SSO_ACCESS_KEY: JMVsA4svqk_TUAjq9jOKy0fLVxBaJpiaAAhcn0gr
  SSO_SECRET_KEY: 39xrdVIpTa65jjPkAB9RCjzdDKN_VY4KdcPkhNjD
  SSO_BUCKET_NAME: windwithlife
  SSO_DOMAIN_NAME: https://images.koudaibook.com



  REDIS_HOST: db.bihuioo.com
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "12345678"

  #Skywalking global config
  SW_AGENT_COLLECTOR_BACKEND_SERVICES: "47.116.67.226:11800"


  CONFIG_SERVER_ADDRESS: "47.116.67.226:8848"
  CONFIG_SERVER_USERNAME: nacos
  CONFIG_SERVER_PASSWORD: nacos
  CONFIG_SERVER_NAMESPACE: public
  CONFIG_SERVER_GROUP_ID:  public

  DISCOVERY_SERVER_ADDRESS: "47.116.67.226:8848"
  DISCOVERY_SERVER_USERNAME: nacos
  DISCOVERY_SERVER_PASSWORD: nacos
  DISCOVERY_SERVER_NAMESPACE: prod-id
  DISCOVERY_SERVER_GROUP_ID:  public


  #database section


  PROD_DATASOURCE_URL: jdbc:mysql://db.bihuioo.com:3306/prod?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
  PROD_DATASOURCE_USERNAME: root
  PROD_DATASOURCE_PASSWORD: root_password



  RELEASE_DATASOURCE_URL: jdbc:mysql://db.bihuioo.com:3306/ops?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8 
  RELEASE_DATASOURCE_USERNAME: root
  RELEASE_DATASOURCE_PASSWORD: root_password

  ACCOUNT_DATASOURCE_URL: jdbc:mysql://db.bihuioo.com:3306/user?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
  ACCOUNT_DATASOURCE_USERNAME: root
  ACCOUNT_DATASOURCE_PASSWORD: root_password

  CMS_DATASOURCE_URL: jdbc:mysql://db.bihuioo.com:3306/prod?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
  CMS_DATASOURCE_USERNAME: root
  CMS_DATASOURCE_PASSWORD: root_password

 

 


 
