
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: routes-ingress-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  tls:
   secretName: api-default-secret
  routes:
  
    - match: Host(`api.thingsminder.com`) && PathPrefix(`/common-service`)
      kind: Rule
      services:
        - name: service-common-service
          port: 80
      middlewares:
        - name: cms-stripprefix   

    - match: Host(`api.thingsminder.com`) && PathPrefix(`/account-service`)
      kind: Rule
      services:
        - name: service-account-service
          port: 80
      middlewares:
        - name: cms-stripprefix    

    - match: Host(`api.thingsminder.com`) && PathPrefix(`/cms-service`)
      kind: Rule
      services:
        - name: service-cms-service
          port: 80
      middlewares:
        - name: cms-stripprefix

    - match: Host(`api.thingsminder.com`) && PathPrefix(`/ops-service`)
      kind: Rule
      services:
        - name: service-ops-service
          port: 80
      middlewares:
        - name: cms-stripprefix   
    - match: Host(`api.thingsminder.com`) && PathPrefix(`/work-order-service`)
      kind: Rule
      services:
        - name: service-work-order-service
          port: 80
      middlewares:
        - name: cms-stripprefix          

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cms-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /common-service
      - /account-service
      - /cms-service
      - /opt-service
      - /work-order-service
     



# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: routes-ingress
#   namespace: default
# spec:
#   entryPoints:
#     - web
#   routes:
  
#     - match: Host(`api.thingsminder.com`) && PathPrefix(`/common-service`)
#       kind: Rule
#       services:
#         - name: service-common-service
#           port: 80
#       middlewares:
#         - name: cms-stripprefix   

#     - match: Host(`api.thingsminder.com`) && PathPrefix(`/account-service`)
#       kind: Rule
#       services:
#         - name: service-account-service
#           port: 80
#       middlewares:
#         - name: cms-stripprefix    

#     - match: Host(`api.thingsminder.com`) && PathPrefix(`/cms-service`)
#       kind: Rule
#       services:
#         - name: service-cms-service
#           port: 80
#       middlewares:
#         - name: cms-stripprefix

#      - match: Host(`api.thingsminder.com`) && PathPrefix(`/ops-service`)
#       kind: Rule
#       services:
#         - name: service-ops-service
#           port: 80
#       middlewares:
#         - name: cms-stripprefix   
#     - match: Host(`api.thingsminder.com`) && PathPrefix(`/work-order-service`)
#       kind: Rule
#       services:
#         - name: service-work-order-service
#           port: 80
#       middlewares:
#         - name: cms-stripprefix   

