apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: default
  labels:
    app: app-account-service
    name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-account-service
      name: account-service
  template:
    metadata:
      labels:
        app: app-account-service
        name: account-service
    spec:
      containers:
        - name: container-account-service
          image: ccr.ccs.tencentyun.com/windwithlife/account-service:latest
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: common-config
          imagePullPolicy: IfNotPresent
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: service-account-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: app-account-service

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-account-service
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/custom-response-headers: "Access-Control-Allow-Origin:*||Access-Control-Allow-Methods:GET,POST,OPTIONS||Access-Control-Allow-Headers:DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,token||Access-Control-Expose-Headers:Content-Length,Content-Range,token"
spec:
  tls:
  - secretName: api-default-secret
    hosts:
    - api.thingsminder.com
  rules:
    - host: api.thingsminder.com
      http:
        paths:
          - path: /account-service
            pathType: Prefix
            backend:
              service:
                name: service-account-service
                port:
                  number: 80    

