
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql8-pvc
spec:
  accessModes:
    - ReadWriteMany
  # 指定 storageClass 的名字，这里使用默认的 standard
  storageClassName: "managed-nfs-storage"
  resources:
    requests:
      storage: 5Gi
        
