apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-default-cert
spec:
  dnsNames:
    - api.xkoudai.com
  secretName: api-default-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-default-cert
spec:
  dnsNames:
    - admin.xkoudai.com
  secretName: admin-default-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-default-cert
spec:
  dnsNames:
    - www.xkoudai.com
  secretName: www-default-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: m-default-cert
spec:
  dnsNames:
    - m.xkoudai.com
  secretName: m-default-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: kube-system
  name: traefik-default-cert
spec:
  dnsNames:
    - traefik.xkoudai.com
  secretName: traefik-default-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer