version: '3'
services:
  kibana:
    image: kibana:8.1.3
    container_name: elk_kibana
    restart: always
    volumes:
      - ./kibana-config.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    privileged: true    #环境变量