apiVersion: v1
kind: ConfigMap
metadata:
  name: database-backup-config
data:
  SPRING_PROFILES_ACTIVE: prod
  SERVER_PORT: "80"

  #database section
  DATABASE_BACKUP_SERVER_HOST: "db.zhangyongqiao.com"
  DATABASE_BACKUP_SERVER_USER: root
  DATABASE_BACKUP_SERVER_PASSWORD: root_password
  DATABASE_BACKUP_PATH: simplex

