
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: routes-ingress-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  tls:
   secretName: api-default-secret
  routes:
  
    - match: Host(`api.koudaibook.com`) && PathPrefix(`/common-service`)
      kind: Rule
      services:
        - name: service-common-service
          port: 80
      middlewares:
        - name: cms-stripprefix   
        - name: cors-header

    - match: Host(`api.koudaibook.com`) && PathPrefix(`/account-service`)
      kind: Rule
      services:
        - name: service-account-service
          port: 80
      middlewares:
        - name: cms-stripprefix
        - name: cors-header    

    - match: Host(`api.koudaibook.com`) && PathPrefix(`/cms-service`)
      kind: Rule
      services:
        - name: service-cms-service
          port: 80
      middlewares:
        - name: cms-stripprefix
        - name: cors-header

 
   
               

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cms-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /common-service
      - /account-service
      - /cms-service
      
     

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors-header
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
      - "POST"
    accessControlAllowOriginList:
      - "*"
    accessControlMaxAge: 100
    accessControlAllowHeaders:
      - "Content-Type"
      - "token"
      - "x-requested-with"
      - "sw8"
      - "sw9"
    accessControlAllowCredentials: true
    addVaryHeader: true



